baseURL = 'http://drewux.com/'
languageCode = 'en-us'
title = 'drew:ux'

[permalinks]
post = ":slug/"
page = ":slug/"

[frontmatter]
date = ["postdate", "date"]

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "drew:ux - Musigns on user experience, accessibility, and leadership"
stylesheet = "assets/css/style.css"
favicon = "assets/img/favicon.ico"
fontawesome = "https://kit.fontawesome.com/26edf67b6e.js"

[params.social]
bluesky = "https://bsky.app/profile/drewtodd.bsky.social"
linkedin = "https://www.linkedin.com/in/andrewtodd"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
    unsafe = true
[markup.highlight]
    codeFences = true
    guessSyntax = false  # Optional: set to true if you want Hugo to guess the language

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
name = "Archives"
url = "/posts/"
weight = 3