baseURL = 'http://drew-ux.com/'
languageCode = 'en-us'
title = 'drew:ux'

theme = "bones"

[permalinks]
post = ":slug/"
page = ":slug/"

[frontmatter]
date = ["postdate", "date"]

[taxonomies]
tag = "tags"
category = "categories"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
name = "Archives"
url = "/posts/"
weight = 3